// generateReport.js — Step 4
// Takes all the results and writes a clean markdown report.
// One section per company. Clear matches or clear "no match".

import fs from 'fs';
import path from 'path';

/**
 * Generates a markdown report from the pipeline results.
 * @param {Array} results - Array of company result objects
 * @returns {string} - Path to the written report file
 */
export async function generateReport(results) {
  const date = new Date().toISOString().split('T')[0]; // e.g. 2025-01-15
  const outputDir = path.resolve(process.cwd(), 'output');
  const reportPath = path.join(outputDir, `job_matches_${date}.md`);

  // Create output dir if it doesn't exist
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Summary counts
  const companiesWithMatches = results.filter(r => r.matches?.length > 0);
  const companiesWithNoMatch = results.filter(r => r.matches?.length === 0 && !r.error);
  const companiesWithErrors = results.filter(r => r.error);
  const totalMatches = results.reduce((sum, r) => sum + (r.matches?.length || 0), 0);

  const lines = [];

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push(`# Job Scout Report`);
  lines.push(`**Run date:** ${date}`);
  lines.push(`**Companies scanned:** ${results.length}`);
  lines.push(`**Total matches found:** ${totalMatches} across ${companiesWithMatches.length} companies`);
  lines.push('');

  // ── Quick Summary ────────────────────────────────────────────────────────────
  lines.push('## Quick Summary');
  lines.push('');

  if (companiesWithMatches.length > 0) {
    lines.push('### ✅ Matches Found');
    for (const r of companiesWithMatches) {
      lines.push(`- **${r.company}** — ${r.matches.length} match${r.matches.length > 1 ? 'es' : ''}: ${r.matches.map(m => m.title).join(', ')}`);
    }
    lines.push('');
  }

  if (companiesWithNoMatch.length > 0) {
    lines.push('### ❌ No Matches');
    lines.push(companiesWithNoMatch.map(r => `- ${r.company}`).join('\n'));
    lines.push('');
  }

  if (companiesWithErrors.length > 0) {
    lines.push('### ⚠️ Errors (check manually)');
    lines.push(companiesWithErrors.map(r => `- ${r.company}: ${r.error}`).join('\n'));
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  // ── Detailed Results ─────────────────────────────────────────────────────────
  lines.push('## Detailed Results');
  lines.push('');

  for (const result of results) {
    lines.push(`### ${result.company}`);

    if (result.careersUrl) {
      lines.push(`**Careers page:** [${result.careersUrl}](${result.careersUrl})`);
    }

    if (result.atsType && result.atsType !== 'mock') {
      lines.push(`**ATS platform:** ${result.atsType}`);
    }

    lines.push('');

    // Error state
    if (result.error) {
      lines.push(`> ⚠️ **Error:** ${result.error}`);
      lines.push('> Check this company\'s careers page manually.');
      lines.push('');
      lines.push('---');
      lines.push('');
      continue;
    }

    // No matches
    if (!result.matches || result.matches.length === 0) {
      lines.push(`> ❌ **No matching roles found.**`);
      if (result.noMatchReason) {
        lines.push(`> ${result.noMatchReason}`);
      }
      lines.push('');
      lines.push('---');
      lines.push('');
      continue;
    }

    // Matches
    lines.push(`**${result.matches.length} match${result.matches.length > 1 ? 'es' : ''} found:**`);
    lines.push('');

    for (let i = 0; i < result.matches.length; i++) {
      const match = result.matches[i];
      lines.push(`#### ${i + 1}. ${match.title}`);
      if (match.score) {
        lines.push(`**Match score:** ${match.score}/100`);
      }
      if (match.location) {
        lines.push(`**Location:** ${match.location}`);
      }
      lines.push(`**Why it matches:** ${match.matchReason}`);
      if (match.url) {
        lines.push(`**Apply:** [View Job Posting](${match.url})`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // ── Footer ───────────────────────────────────────────────────────────────────
  lines.push('## Notes');
  lines.push('');
  lines.push('- This report was generated automatically. Always verify job postings are still live before applying.');
  lines.push('- To add companies, edit `companies.txt`');
  lines.push('- To update your criteria, edit `criteria.md`');
  lines.push('- To override a careers URL manually, add to `custom_urls.json`');
  lines.push('');
  lines.push(`*Generated by Job Scout on ${new Date().toLocaleString()}*`);

  // Write the file
  fs.writeFileSync(reportPath, lines.join('\n'), 'utf-8');

  return reportPath;
}
